config/routes.rb
IB::Engine.routes.draw do
  # resources :bars, :module => "ib"
  resources :bars
  resources :combo_legs
  resources :contracts
  resources :contract_details
  resources :executions
  resources :orders
  resources :order_states
  resources :underlyings

  root :to => "underlyings#index"
end

app/controllers/ib/application_controller.rb
module Ib
  class ApplicationController <
    defined?(::ApplicationController) ? ::ApplicationController :  ActionController::Base
  end
end

app/controllers/ib/bars_controller.rb
require_dependency "ib/application_controller"

module Ib
  class BarsController < ApplicationController
    # GET /bars
    # GET /bars.json
    def index
      @bars = Bar.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @bars }
      end
    end
  
    # GET /bars/1
    # GET /bars/1.json
    def show
      @bar = Bar.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @bar }
      end
    end
  
    # GET /bars/new
    # GET /bars/new.json
    def new
      @bar = Bar.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @bar }
      end
    end
  
    # GET /bars/1/edit
    def edit
      @bar = Bar.find(params[:id])
    end
  
    # POST /bars
    # POST /bars.json
    def create
      @bar = Bar.new(params[:bar])
  
      respond_to do |format|
        if @bar.save
          format.html { redirect_to @bar, :notice => 'Bar was successfully created.' }
          format.json { render :json => @bar, :status => :created, :location => @bar }
        else
          format.html { render :action => "new" }
          format.json { render :json => @bar.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /bars/1
    # PUT /bars/1.json
    def update
      @bar = Bar.find(params[:id])
  
      respond_to do |format|
        if @bar.update_attributes(params[:bar])
          format.html { redirect_to @bar, :notice => 'Bar was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @bar.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /bars/1
    # DELETE /bars/1.json
    def destroy
      @bar = Bar.find(params[:id])
      @bar.destroy
  
      respond_to do |format|
        format.html { redirect_to bars_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/combo_legs_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ComboLegsController < ApplicationController
    # GET /combo_legs
    # GET /combo_legs.json
    def index
      @combo_legs = ComboLeg.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @combo_legs }
      end
    end
  
    # GET /combo_legs/1
    # GET /combo_legs/1.json
    def show
      @combo_leg = ComboLeg.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @combo_leg }
      end
    end
  
    # GET /combo_legs/new
    # GET /combo_legs/new.json
    def new
      @combo_leg = ComboLeg.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @combo_leg }
      end
    end
  
    # GET /combo_legs/1/edit
    def edit
      @combo_leg = ComboLeg.find(params[:id])
    end
  
    # POST /combo_legs
    # POST /combo_legs.json
    def create
      @combo_leg = ComboLeg.new(params[:combo_leg])
  
      respond_to do |format|
        if @combo_leg.save
          format.html { redirect_to @combo_leg, :notice => 'Combo leg was successfully created.' }
          format.json { render :json => @combo_leg, :status => :created, :location => @combo_leg }
        else
          format.html { render :action => "new" }
          format.json { render :json => @combo_leg.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /combo_legs/1
    # PUT /combo_legs/1.json
    def update
      @combo_leg = ComboLeg.find(params[:id])
  
      respond_to do |format|
        if @combo_leg.update_attributes(params[:combo_leg])
          format.html { redirect_to @combo_leg, :notice => 'Combo leg was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @combo_leg.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /combo_legs/1
    # DELETE /combo_legs/1.json
    def destroy
      @combo_leg = ComboLeg.find(params[:id])
      @combo_leg.destroy
  
      respond_to do |format|
        format.html { redirect_to combo_legs_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/contract_details_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ContractDetailsController < ApplicationController
    # GET /contract_details
    # GET /contract_details.json
    def index
      @contract_details = ContractDetail.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @contract_details }
      end
    end
  
    # GET /contract_details/1
    # GET /contract_details/1.json
    def show
      @contract_detail = ContractDetail.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @contract_detail }
      end
    end
  
    # GET /contract_details/new
    # GET /contract_details/new.json
    def new
      @contract_detail = ContractDetail.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @contract_detail }
      end
    end
  
    # GET /contract_details/1/edit
    def edit
      @contract_detail = ContractDetail.find(params[:id])
    end
  
    # POST /contract_details
    # POST /contract_details.json
    def create
      @contract_detail = ContractDetail.new(params[:contract_detail])
  
      respond_to do |format|
        if @contract_detail.save
          format.html { redirect_to @contract_detail, :notice => 'Contract detail was successfully created.' }
          format.json { render :json => @contract_detail, :status => :created, :location => @contract_detail }
        else
          format.html { render :action => "new" }
          format.json { render :json => @contract_detail.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /contract_details/1
    # PUT /contract_details/1.json
    def update
      @contract_detail = ContractDetail.find(params[:id])
  
      respond_to do |format|
        if @contract_detail.update_attributes(params[:contract_detail])
          format.html { redirect_to @contract_detail, :notice => 'Contract detail was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @contract_detail.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /contract_details/1
    # DELETE /contract_details/1.json
    def destroy
      @contract_detail = ContractDetail.find(params[:id])
      @contract_detail.destroy
  
      respond_to do |format|
        format.html { redirect_to contract_details_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/contracts_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ContractsController < ApplicationController
    # GET /contracts
    # GET /contracts.json
    def index
      @contracts = Contract.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @contracts }
      end
    end
  
    # GET /contracts/1
    # GET /contracts/1.json
    def show
      @contract = Contract.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @contract }
      end
    end
  
    # GET /contracts/new
    # GET /contracts/new.json
    def new
      @contract = Contract.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @contract }
      end
    end
  
    # GET /contracts/1/edit
    def edit
      @contract = Contract.find(params[:id])
    end
  
    # POST /contracts
    # POST /contracts.json
    def create
      @contract = Contract.new(params[:contract])
  
      respond_to do |format|
        if @contract.save
          format.html { redirect_to @contract, :notice => 'Contract was successfully created.' }
          format.json { render :json => @contract, :status => :created, :location => @contract }
        else
          format.html { render :action => "new" }
          format.json { render :json => @contract.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /contracts/1
    # PUT /contracts/1.json
    def update
      @contract = Contract.find(params[:id])
  
      respond_to do |format|
        if @contract.update_attributes(params[:contract])
          format.html { redirect_to @contract, :notice => 'Contract was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @contract.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /contracts/1
    # DELETE /contracts/1.json
    def destroy
      @contract = Contract.find(params[:id])
      @contract.destroy
  
      respond_to do |format|
        format.html { redirect_to contracts_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/executions_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ExecutionsController < ApplicationController
    # GET /executions
    # GET /executions.json
    def index
      @executions = Execution.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @executions }
      end
    end
  
    # GET /executions/1
    # GET /executions/1.json
    def show
      @execution = Execution.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @execution }
      end
    end
  
    # GET /executions/new
    # GET /executions/new.json
    def new
      @execution = Execution.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @execution }
      end
    end
  
    # GET /executions/1/edit
    def edit
      @execution = Execution.find(params[:id])
    end
  
    # POST /executions
    # POST /executions.json
    def create
      @execution = Execution.new(params[:execution])
  
      respond_to do |format|
        if @execution.save
          format.html { redirect_to @execution, :notice => 'Execution was successfully created.' }
          format.json { render :json => @execution, :status => :created, :location => @execution }
        else
          format.html { render :action => "new" }
          format.json { render :json => @execution.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /executions/1
    # PUT /executions/1.json
    def update
      @execution = Execution.find(params[:id])
  
      respond_to do |format|
        if @execution.update_attributes(params[:execution])
          format.html { redirect_to @execution, :notice => 'Execution was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @execution.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /executions/1
    # DELETE /executions/1.json
    def destroy
      @execution = Execution.find(params[:id])
      @execution.destroy
  
      respond_to do |format|
        format.html { redirect_to executions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/order_states_controller.rb
require_dependency "ib/application_controller"

module Ib
  class OrderStatesController < ApplicationController
    # GET /order_states
    # GET /order_states.json
    def index
      @order_states = OrderState.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @order_states }
      end
    end
  
    # GET /order_states/1
    # GET /order_states/1.json
    def show
      @order_state = OrderState.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @order_state }
      end
    end
  
    # GET /order_states/new
    # GET /order_states/new.json
    def new
      @order_state = OrderState.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @order_state }
      end
    end
  
    # GET /order_states/1/edit
    def edit
      @order_state = OrderState.find(params[:id])
    end
  
    # POST /order_states
    # POST /order_states.json
    def create
      @order_state = OrderState.new(params[:order_state])
  
      respond_to do |format|
        if @order_state.save
          format.html { redirect_to @order_state, :notice => 'Order state was successfully created.' }
          format.json { render :json => @order_state, :status => :created, :location => @order_state }
        else
          format.html { render :action => "new" }
          format.json { render :json => @order_state.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /order_states/1
    # PUT /order_states/1.json
    def update
      @order_state = OrderState.find(params[:id])
  
      respond_to do |format|
        if @order_state.update_attributes(params[:order_state])
          format.html { redirect_to @order_state, :notice => 'Order state was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @order_state.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /order_states/1
    # DELETE /order_states/1.json
    def destroy
      @order_state = OrderState.find(params[:id])
      @order_state.destroy
  
      respond_to do |format|
        format.html { redirect_to order_states_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/orders_controller.rb
require_dependency "ib/application_controller"

module Ib
  class OrdersController < ApplicationController
    # GET /orders
    # GET /orders.json
    def index
      @orders = Order.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @orders }
      end
    end
  
    # GET /orders/1
    # GET /orders/1.json
    def show
      @order = Order.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @order }
      end
    end
  
    # GET /orders/new
    # GET /orders/new.json
    def new
      @order = Order.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @order }
      end
    end
  
    # GET /orders/1/edit
    def edit
      @order = Order.find(params[:id])
    end
  
    # POST /orders
    # POST /orders.json
    def create
      @order = Order.new(params[:order])
  
      respond_to do |format|
        if @order.save
          format.html { redirect_to @order, :notice => 'Order was successfully created.' }
          format.json { render :json => @order, :status => :created, :location => @order }
        else
          format.html { render :action => "new" }
          format.json { render :json => @order.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /orders/1
    # PUT /orders/1.json
    def update
      @order = Order.find(params[:id])
  
      respond_to do |format|
        if @order.update_attributes(params[:order])
          format.html { redirect_to @order, :notice => 'Order was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @order.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /orders/1
    # DELETE /orders/1.json
    def destroy
      @order = Order.find(params[:id])
      @order.destroy
  
      respond_to do |format|
        format.html { redirect_to orders_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/ib/application_helper.rb
module Ib
  module ApplicationHelper
  end
end

app/helpers/ib/bars_helper.rb
module Ib
  module BarsHelper
  end
end

app/helpers/ib/combo_legs_helper.rb
module Ib
  module ComboLegsHelper
  end
end

app/helpers/ib/contract_details_helper.rb
module Ib
  module ContractDetailsHelper
  end
end

app/helpers/ib/contracts_helper.rb
module Ib
  module ContractsHelper
  end
end

app/helpers/ib/executions_helper.rb
module Ib
  module ExecutionsHelper
  end
end

app/helpers/ib/order_states_helper.rb
module Ib
  module OrderStatesHelper
  end
end

app/helpers/ib/orders_helper.rb
module Ib
  module OrdersHelper
  end
end

app/helpers/ib/underlyings_helper.rb
module Ib
  module UnderlyingsHelper
  end
end

app/views/ib/order_states/_form.html.erb
<%= form_for(@order_state) do |f| %>
  <% if @order_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_state.errors.count, "error") %> prohibited this order_state from being saved:</h2>

      <ul>
      <% @order_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :local_id %><br />
    <%= f.number_field :local_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :perm_id %><br />
    <%= f.number_field :perm_id %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :filled %><br />
    <%= f.number_field :filled %>
  </div>
  <div class="field">
    <%= f.label :remaining %><br />
    <%= f.number_field :remaining %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :average_price %><br />
    <%= f.text_field :average_price %>
  </div>
  <div class="field">
    <%= f.label :why_held %><br />
    <%= f.text_field :why_held %>
  </div>
  <div class="field">
    <%= f.label :warning_text %><br />
    <%= f.text_field :warning_text %>
  </div>
  <div class="field">
    <%= f.label :commission_currency %><br />
    <%= f.text_field :commission_currency %>
  </div>
  <div class="field">
    <%= f.label :commission %><br />
    <%= f.text_field :commission %>
  </div>
  <div class="field">
    <%= f.label :min_commission %><br />
    <%= f.text_field :min_commission %>
  </div>
  <div class="field">
    <%= f.label :max_commission %><br />
    <%= f.text_field :max_commission %>
  </div>
  <div class="field">
    <%= f.label :init_margin %><br />
    <%= f.text_field :init_margin %>
  </div>
  <div class="field">
    <%= f.label :maint_margin %><br />
    <%= f.text_field :maint_margin %>
  </div>
  <div class="field">
    <%= f.label :equity_with_loan %><br />
    <%= f.text_field :equity_with_loan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ib/order_states/edit.html.erb
<h1>Editing Order State</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_state %> |
<%= link_to 'Back', order_states_path %>

app/views/ib/order_states/index.html.erb
<h1>Listing Order States</h1>

<table>
  <tr>
    <th>Order</th>
    <th>Local</th>
    <th>Client</th>
    <th>Perm</th>
    <th>Parent</th>
    <th>Status</th>
    <th>Filled</th>
    <th>Remaining</th>
    <th>Price</th>
    <th>Average price</th>
    <th>Why held</th>
    <th>Warning text</th>
    <th>Commission currency</th>
    <th>Commission</th>
    <th>Min commission</th>
    <th>Max commission</th>
    <th>Init margin</th>
    <th>Maint margin</th>
    <th>Equity with loan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @order_states.each do |order_state| %>
  <tr>
    <td><%= order_state.order_id %></td>
    <td><%= order_state.local_id %></td>
    <td><%= order_state.client_id %></td>
    <td><%= order_state.perm_id %></td>
    <td><%= order_state.parent_id %></td>
    <td><%= order_state.status %></td>
    <td><%= order_state.filled %></td>
    <td><%= order_state.remaining %></td>
    <td><%= order_state.price %></td>
    <td><%= order_state.average_price %></td>
    <td><%= order_state.why_held %></td>
    <td><%= order_state.warning_text %></td>
    <td><%= order_state.commission_currency %></td>
    <td><%= order_state.commission %></td>
    <td><%= order_state.min_commission %></td>
    <td><%= order_state.max_commission %></td>
    <td><%= order_state.init_margin %></td>
    <td><%= order_state.maint_margin %></td>
    <td><%= order_state.equity_with_loan %></td>
    <td><%= link_to 'Show', order_state %></td>
    <td><%= link_to 'Edit', edit_order_state_path(order_state) %></td>
    <td><%= link_to 'Destroy', order_state, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order State', new_order_state_path %>

app/views/ib/order_states/new.html.erb
<h1>New Order State</h1>

<%= render 'form' %>

<%= link_to 'Back', order_states_path %>

app/views/ib/order_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Order:</b>
  <%= @order_state.order_id %>
</p>

<p>
  <b>Local:</b>
  <%= @order_state.local_id %>
</p>

<p>
  <b>Client:</b>
  <%= @order_state.client_id %>
</p>

<p>
  <b>Perm:</b>
  <%= @order_state.perm_id %>
</p>

<p>
  <b>Parent:</b>
  <%= @order_state.parent_id %>
</p>

<p>
  <b>Status:</b>
  <%= @order_state.status %>
</p>

<p>
  <b>Filled:</b>
  <%= @order_state.filled %>
</p>

<p>
  <b>Remaining:</b>
  <%= @order_state.remaining %>
</p>

<p>
  <b>Price:</b>
  <%= @order_state.price %>
</p>

<p>
  <b>Average price:</b>
  <%= @order_state.average_price %>
</p>

<p>
  <b>Why held:</b>
  <%= @order_state.why_held %>
</p>

<p>
  <b>Warning text:</b>
  <%= @order_state.warning_text %>
</p>

<p>
  <b>Commission currency:</b>
  <%= @order_state.commission_currency %>
</p>

<p>
  <b>Commission:</b>
  <%= @order_state.commission %>
</p>

<p>
  <b>Min commission:</b>
  <%= @order_state.min_commission %>
</p>

<p>
  <b>Max commission:</b>
  <%= @order_state.max_commission %>
</p>

<p>
  <b>Init margin:</b>
  <%= @order_state.init_margin %>
</p>

<p>
  <b>Maint margin:</b>
  <%= @order_state.maint_margin %>
</p>

<p>
  <b>Equity with loan:</b>
  <%= @order_state.equity_with_loan %>
</p>


<%= link_to 'Edit', edit_order_state_path(@order_state) %> |
<%= link_to 'Back', order_states_path %>