config/routes.rb
IB::Engine.routes.draw do
  # resources :bars, :module => "ib"
  resources :bars
  resources :combo_legs
  resources :contracts
  resources :contract_details
  resources :executions
  resources :orders
  resources :order_states
  resources :underlyings

  root :to => "underlyings#index"
end

app/controllers/ib/application_controller.rb
module Ib
  class ApplicationController <
    defined?(::ApplicationController) ? ::ApplicationController :  ActionController::Base
  end
end

app/controllers/ib/bars_controller.rb
require_dependency "ib/application_controller"

module Ib
  class BarsController < ApplicationController
    # GET /bars
    # GET /bars.json
    def index
      @bars = Bar.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @bars }
      end
    end
  
    # GET /bars/1
    # GET /bars/1.json
    def show
      @bar = Bar.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @bar }
      end
    end
  
    # GET /bars/new
    # GET /bars/new.json
    def new
      @bar = Bar.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @bar }
      end
    end
  
    # GET /bars/1/edit
    def edit
      @bar = Bar.find(params[:id])
    end
  
    # POST /bars
    # POST /bars.json
    def create
      @bar = Bar.new(params[:bar])
  
      respond_to do |format|
        if @bar.save
          format.html { redirect_to @bar, :notice => 'Bar was successfully created.' }
          format.json { render :json => @bar, :status => :created, :location => @bar }
        else
          format.html { render :action => "new" }
          format.json { render :json => @bar.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /bars/1
    # PUT /bars/1.json
    def update
      @bar = Bar.find(params[:id])
  
      respond_to do |format|
        if @bar.update_attributes(params[:bar])
          format.html { redirect_to @bar, :notice => 'Bar was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @bar.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /bars/1
    # DELETE /bars/1.json
    def destroy
      @bar = Bar.find(params[:id])
      @bar.destroy
  
      respond_to do |format|
        format.html { redirect_to bars_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/combo_legs_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ComboLegsController < ApplicationController
    # GET /combo_legs
    # GET /combo_legs.json
    def index
      @combo_legs = ComboLeg.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @combo_legs }
      end
    end
  
    # GET /combo_legs/1
    # GET /combo_legs/1.json
    def show
      @combo_leg = ComboLeg.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @combo_leg }
      end
    end
  
    # GET /combo_legs/new
    # GET /combo_legs/new.json
    def new
      @combo_leg = ComboLeg.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @combo_leg }
      end
    end
  
    # GET /combo_legs/1/edit
    def edit
      @combo_leg = ComboLeg.find(params[:id])
    end
  
    # POST /combo_legs
    # POST /combo_legs.json
    def create
      @combo_leg = ComboLeg.new(params[:combo_leg])
  
      respond_to do |format|
        if @combo_leg.save
          format.html { redirect_to @combo_leg, :notice => 'Combo leg was successfully created.' }
          format.json { render :json => @combo_leg, :status => :created, :location => @combo_leg }
        else
          format.html { render :action => "new" }
          format.json { render :json => @combo_leg.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /combo_legs/1
    # PUT /combo_legs/1.json
    def update
      @combo_leg = ComboLeg.find(params[:id])
  
      respond_to do |format|
        if @combo_leg.update_attributes(params[:combo_leg])
          format.html { redirect_to @combo_leg, :notice => 'Combo leg was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @combo_leg.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /combo_legs/1
    # DELETE /combo_legs/1.json
    def destroy
      @combo_leg = ComboLeg.find(params[:id])
      @combo_leg.destroy
  
      respond_to do |format|
        format.html { redirect_to combo_legs_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/contract_details_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ContractDetailsController < ApplicationController
    # GET /contract_details
    # GET /contract_details.json
    def index
      @contract_details = ContractDetail.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @contract_details }
      end
    end
  
    # GET /contract_details/1
    # GET /contract_details/1.json
    def show
      @contract_detail = ContractDetail.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @contract_detail }
      end
    end
  
    # GET /contract_details/new
    # GET /contract_details/new.json
    def new
      @contract_detail = ContractDetail.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @contract_detail }
      end
    end
  
    # GET /contract_details/1/edit
    def edit
      @contract_detail = ContractDetail.find(params[:id])
    end
  
    # POST /contract_details
    # POST /contract_details.json
    def create
      @contract_detail = ContractDetail.new(params[:contract_detail])
  
      respond_to do |format|
        if @contract_detail.save
          format.html { redirect_to @contract_detail, :notice => 'Contract detail was successfully created.' }
          format.json { render :json => @contract_detail, :status => :created, :location => @contract_detail }
        else
          format.html { render :action => "new" }
          format.json { render :json => @contract_detail.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /contract_details/1
    # PUT /contract_details/1.json
    def update
      @contract_detail = ContractDetail.find(params[:id])
  
      respond_to do |format|
        if @contract_detail.update_attributes(params[:contract_detail])
          format.html { redirect_to @contract_detail, :notice => 'Contract detail was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @contract_detail.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /contract_details/1
    # DELETE /contract_details/1.json
    def destroy
      @contract_detail = ContractDetail.find(params[:id])
      @contract_detail.destroy
  
      respond_to do |format|
        format.html { redirect_to contract_details_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/contracts_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ContractsController < ApplicationController
    # GET /contracts
    # GET /contracts.json
    def index
      @contracts = Contract.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @contracts }
      end
    end
  
    # GET /contracts/1
    # GET /contracts/1.json
    def show
      @contract = Contract.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @contract }
      end
    end
  
    # GET /contracts/new
    # GET /contracts/new.json
    def new
      @contract = Contract.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @contract }
      end
    end
  
    # GET /contracts/1/edit
    def edit
      @contract = Contract.find(params[:id])
    end
  
    # POST /contracts
    # POST /contracts.json
    def create
      @contract = Contract.new(params[:contract])
  
      respond_to do |format|
        if @contract.save
          format.html { redirect_to @contract, :notice => 'Contract was successfully created.' }
          format.json { render :json => @contract, :status => :created, :location => @contract }
        else
          format.html { render :action => "new" }
          format.json { render :json => @contract.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /contracts/1
    # PUT /contracts/1.json
    def update
      @contract = Contract.find(params[:id])
  
      respond_to do |format|
        if @contract.update_attributes(params[:contract])
          format.html { redirect_to @contract, :notice => 'Contract was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @contract.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /contracts/1
    # DELETE /contracts/1.json
    def destroy
      @contract = Contract.find(params[:id])
      @contract.destroy
  
      respond_to do |format|
        format.html { redirect_to contracts_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/executions_controller.rb
require_dependency "ib/application_controller"

module Ib
  class ExecutionsController < ApplicationController
    # GET /executions
    # GET /executions.json
    def index
      @executions = Execution.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @executions }
      end
    end
  
    # GET /executions/1
    # GET /executions/1.json
    def show
      @execution = Execution.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @execution }
      end
    end
  
    # GET /executions/new
    # GET /executions/new.json
    def new
      @execution = Execution.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @execution }
      end
    end
  
    # GET /executions/1/edit
    def edit
      @execution = Execution.find(params[:id])
    end
  
    # POST /executions
    # POST /executions.json
    def create
      @execution = Execution.new(params[:execution])
  
      respond_to do |format|
        if @execution.save
          format.html { redirect_to @execution, :notice => 'Execution was successfully created.' }
          format.json { render :json => @execution, :status => :created, :location => @execution }
        else
          format.html { render :action => "new" }
          format.json { render :json => @execution.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /executions/1
    # PUT /executions/1.json
    def update
      @execution = Execution.find(params[:id])
  
      respond_to do |format|
        if @execution.update_attributes(params[:execution])
          format.html { redirect_to @execution, :notice => 'Execution was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @execution.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /executions/1
    # DELETE /executions/1.json
    def destroy
      @execution = Execution.find(params[:id])
      @execution.destroy
  
      respond_to do |format|
        format.html { redirect_to executions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/order_states_controller.rb
require_dependency "ib/application_controller"

module Ib
  class OrderStatesController < ApplicationController
    # GET /order_states
    # GET /order_states.json
    def index
      @order_states = OrderState.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @order_states }
      end
    end
  
    # GET /order_states/1
    # GET /order_states/1.json
    def show
      @order_state = OrderState.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @order_state }
      end
    end
  
    # GET /order_states/new
    # GET /order_states/new.json
    def new
      @order_state = OrderState.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @order_state }
      end
    end
  
    # GET /order_states/1/edit
    def edit
      @order_state = OrderState.find(params[:id])
    end
  
    # POST /order_states
    # POST /order_states.json
    def create
      @order_state = OrderState.new(params[:order_state])
  
      respond_to do |format|
        if @order_state.save
          format.html { redirect_to @order_state, :notice => 'Order state was successfully created.' }
          format.json { render :json => @order_state, :status => :created, :location => @order_state }
        else
          format.html { render :action => "new" }
          format.json { render :json => @order_state.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /order_states/1
    # PUT /order_states/1.json
    def update
      @order_state = OrderState.find(params[:id])
  
      respond_to do |format|
        if @order_state.update_attributes(params[:order_state])
          format.html { redirect_to @order_state, :notice => 'Order state was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @order_state.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /order_states/1
    # DELETE /order_states/1.json
    def destroy
      @order_state = OrderState.find(params[:id])
      @order_state.destroy
  
      respond_to do |format|
        format.html { redirect_to order_states_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/ib/orders_controller.rb
require_dependency "ib/application_controller"

module Ib
  class OrdersController < ApplicationController
    # GET /orders
    # GET /orders.json
    def index
      @orders = Order.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @orders }
      end
    end
  
    # GET /orders/1
    # GET /orders/1.json
    def show
      @order = Order.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @order }
      end
    end
  
    # GET /orders/new
    # GET /orders/new.json
    def new
      @order = Order.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @order }
      end
    end
  
    # GET /orders/1/edit
    def edit
      @order = Order.find(params[:id])
    end
  
    # POST /orders
    # POST /orders.json
    def create
      @order = Order.new(params[:order])
  
      respond_to do |format|
        if @order.save
          format.html { redirect_to @order, :notice => 'Order was successfully created.' }
          format.json { render :json => @order, :status => :created, :location => @order }
        else
          format.html { render :action => "new" }
          format.json { render :json => @order.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /orders/1
    # PUT /orders/1.json
    def update
      @order = Order.find(params[:id])
  
      respond_to do |format|
        if @order.update_attributes(params[:order])
          format.html { redirect_to @order, :notice => 'Order was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @order.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /orders/1
    # DELETE /orders/1.json
    def destroy
      @order = Order.find(params[:id])
      @order.destroy
  
      respond_to do |format|
        format.html { redirect_to orders_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/ib/application_helper.rb
module Ib
  module ApplicationHelper
  end
end

app/helpers/ib/bars_helper.rb
module Ib
  module BarsHelper
  end
end

app/helpers/ib/combo_legs_helper.rb
module Ib
  module ComboLegsHelper
  end
end

app/helpers/ib/contract_details_helper.rb
module Ib
  module ContractDetailsHelper
  end
end

app/helpers/ib/contracts_helper.rb
module Ib
  module ContractsHelper
  end
end

app/helpers/ib/executions_helper.rb
module Ib
  module ExecutionsHelper
  end
end

app/helpers/ib/order_states_helper.rb
module Ib
  module OrderStatesHelper
  end
end

app/helpers/ib/orders_helper.rb
module Ib
  module OrdersHelper
  end
end

app/helpers/ib/underlyings_helper.rb
module Ib
  module UnderlyingsHelper
  end
end

app/views/ib/contract_details/_form.html.erb
<%= form_for(@contract_detail) do |f| %>
  <% if @contract_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract_detail.errors.count, "error") %> prohibited this contract_detail from being saved:</h2>

      <ul>
      <% @contract_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contract_id %><br />
    <%= f.number_field :contract_id %>
  </div>
  <div class="field">
    <%= f.label :market_name %><br />
    <%= f.text_field :market_name %>
  </div>
  <div class="field">
    <%= f.label :trading_class %><br />
    <%= f.text_field :trading_class %>
  </div>
  <div class="field">
    <%= f.label :min_tick %><br />
    <%= f.text_field :min_tick %>
  </div>
  <div class="field">
    <%= f.label :price_magnifier %><br />
    <%= f.number_field :price_magnifier %>
  </div>
  <div class="field">
    <%= f.label :order_types %><br />
    <%= f.text_field :order_types %>
  </div>
  <div class="field">
    <%= f.label :valid_exchanges %><br />
    <%= f.text_field :valid_exchanges %>
  </div>
  <div class="field">
    <%= f.label :under_con_id %><br />
    <%= f.number_field :under_con_id %>
  </div>
  <div class="field">
    <%= f.label :long_name %><br />
    <%= f.text_field :long_name %>
  </div>
  <div class="field">
    <%= f.label :contract_month %><br />
    <%= f.text_field :contract_month %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.text_field :time_zone %>
  </div>
  <div class="field">
    <%= f.label :trading_hours %><br />
    <%= f.text_field :trading_hours %>
  </div>
  <div class="field">
    <%= f.label :liquid_hours %><br />
    <%= f.text_field :liquid_hours %>
  </div>
  <div class="field">
    <%= f.label :cusip %><br />
    <%= f.text_field :cusip %>
  </div>
  <div class="field">
    <%= f.label :ratings %><br />
    <%= f.text_field :ratings %>
  </div>
  <div class="field">
    <%= f.label :desc_append %><br />
    <%= f.text_field :desc_append %>
  </div>
  <div class="field">
    <%= f.label :bond_type %><br />
    <%= f.text_field :bond_type %>
  </div>
  <div class="field">
    <%= f.label :coupon_type %><br />
    <%= f.text_field :coupon_type %>
  </div>
  <div class="field">
    <%= f.label :coupon %><br />
    <%= f.text_field :coupon %>
  </div>
  <div class="field">
    <%= f.label :maturity %><br />
    <%= f.text_field :maturity %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br />
    <%= f.text_field :issue_date %>
  </div>
  <div class="field">
    <%= f.label :next_option_date %><br />
    <%= f.text_field :next_option_date %>
  </div>
  <div class="field">
    <%= f.label :next_option_type %><br />
    <%= f.text_field :next_option_type %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :callable %><br />
    <%= f.check_box :callable %>
  </div>
  <div class="field">
    <%= f.label :puttable %><br />
    <%= f.check_box :puttable %>
  </div>
  <div class="field">
    <%= f.label :convertible %><br />
    <%= f.check_box :convertible %>
  </div>
  <div class="field">
    <%= f.label :next_option_partial %><br />
    <%= f.check_box :next_option_partial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ib/contract_details/edit.html.erb
<h1>Editing contract_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract_detail %> |
<%= link_to 'Back', contract_details_path %>

app/views/ib/contract_details/index.html.erb
<h1>Listing contract_details</h1>

<table>
  <tr>
    <th>Contract</th>
    <th>Market name</th>
    <th>Trading class</th>
    <th>Min tick</th>
    <th>Price magnifier</th>
    <th>Order types</th>
    <th>Valid exchanges</th>
    <th>Under con</th>
    <th>Long name</th>
    <th>Contract month</th>
    <th>Industry</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Time zone</th>
    <th>Trading hours</th>
    <th>Liquid hours</th>
    <th>Cusip</th>
    <th>Ratings</th>
    <th>Desc append</th>
    <th>Bond type</th>
    <th>Oupon type</th>
    <th>Coupon</th>
    <th>Maturity</th>
    <th>Issue date</th>
    <th>Next option date</th>
    <th>Next option type</th>
    <th>Notes</th>
    <th>Callable</th>
    <th>Puttable</th>
    <th>Convertible</th>
    <th>Next option partial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contract_details.each do |contract_detail| %>
  <tr>
    <td><%= contract_detail.contract_id %></td>
    <td><%= contract_detail.market_name %></td>
    <td><%= contract_detail.trading_class %></td>
    <td><%= contract_detail.min_tick %></td>
    <td><%= contract_detail.price_magnifier %></td>
    <td><%= contract_detail.order_types %></td>
    <td><%= contract_detail.valid_exchanges %></td>
    <td><%= contract_detail.under_con_id %></td>
    <td><%= contract_detail.long_name %></td>
    <td><%= contract_detail.contract_month %></td>
    <td><%= contract_detail.industry %></td>
    <td><%= contract_detail.category %></td>
    <td><%= contract_detail.subcategory %></td>
    <td><%= contract_detail.time_zone %></td>
    <td><%= contract_detail.trading_hours %></td>
    <td><%= contract_detail.liquid_hours %></td>
    <td><%= contract_detail.cusip %></td>
    <td><%= contract_detail.ratings %></td>
    <td><%= contract_detail.desc_append %></td>
    <td><%= contract_detail.bond_type %></td>
    <td><%= contract_detail.coupon_type %></td>
    <td><%= contract_detail.coupon %></td>
    <td><%= contract_detail.maturity %></td>
    <td><%= contract_detail.issue_date %></td>
    <td><%= contract_detail.next_option_date %></td>
    <td><%= contract_detail.next_option_type %></td>
    <td><%= contract_detail.notes %></td>
    <td><%= contract_detail.callable %></td>
    <td><%= contract_detail.puttable %></td>
    <td><%= contract_detail.convertible %></td>
    <td><%= contract_detail.next_option_partial %></td>
    <td><%= link_to 'Show', contract_detail %></td>
    <td><%= link_to 'Edit', edit_contract_detail_path(contract_detail) %></td>
    <td><%= link_to 'Destroy', contract_detail, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contract Detail', new_contract_detail_path %>

app/views/ib/contract_details/new.html.erb
<h1>New Contract Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', contract_details_path %>

app/views/ib/contract_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contract:</b>
  <%= @contract_detail.contract_id %>
</p>

<p>
  <b>Market name:</b>
  <%= @contract_detail.market_name %>
</p>

<p>
  <b>Trading class:</b>
  <%= @contract_detail.trading_class %>
</p>

<p>
  <b>Min tick:</b>
  <%= @contract_detail.min_tick %>
</p>

<p>
  <b>Price magnifier:</b>
  <%= @contract_detail.price_magnifier %>
</p>

<p>
  <b>Order types:</b>
  <%= @contract_detail.order_types %>
</p>

<p>
  <b>Valid exchanges:</b>
  <%= @contract_detail.valid_exchanges %>
</p>

<p>
  <b>Under con:</b>
  <%= @contract_detail.under_con_id %>
</p>

<p>
  <b>Long name:</b>
  <%= @contract_detail.long_name %>
</p>

<p>
  <b>Contract month:</b>
  <%= @contract_detail.contract_month %>
</p>

<p>
  <b>Industry:</b>
  <%= @contract_detail.industry %>
</p>

<p>
  <b>Category:</b>
  <%= @contract_detail.category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @contract_detail.subcategory %>
</p>

<p>
  <b>Time zone:</b>
  <%= @contract_detail.time_zone %>
</p>

<p>
  <b>Trading hours:</b>
  <%= @contract_detail.trading_hours %>
</p>

<p>
  <b>Liquid hours:</b>
  <%= @contract_detail.liquid_hours %>
</p>

<p>
  <b>Cusip:</b>
  <%= @contract_detail.cusip %>
</p>

<p>
  <b>Ratings:</b>
  <%= @contract_detail.ratings %>
</p>

<p>
  <b>Desc append:</b>
  <%= @contract_detail.desc_append %>
</p>

<p>
  <b>Bond type:</b>
  <%= @contract_detail.bond_type %>
</p>

<p>
  <b>Coupon type:</b>
  <%= @contract_detail.coupon_type %>
</p>

<p>
  <b>Coupon:</b>
  <%= @contract_detail.coupon %>
</p>

<p>
  <b>Maturity:</b>
  <%= @contract_detail.maturity %>
</p>

<p>
  <b>Issue date:</b>
  <%= @contract_detail.issue_date %>
</p>

<p>
  <b>Next option date:</b>
  <%= @contract_detail.next_option_date %>
</p>

<p>
  <b>Next option type:</b>
  <%= @contract_detail.next_option_type %>
</p>

<p>
  <b>Notes:</b>
  <%= @contract_detail.notes %>
</p>

<p>
  <b>Callable:</b>
  <%= @contract_detail.callable %>
</p>

<p>
  <b>Puttable:</b>
  <%= @contract_detail.puttable %>
</p>

<p>
  <b>Convertible:</b>
  <%= @contract_detail.convertible %>
</p>

<p>
  <b>Next option partial:</b>
  <%= @contract_detail.next_option_partial %>
</p>


<%= link_to 'Edit', edit_contract_detail_path(@contract_detail) %> |
<%= link_to 'Back', contract_details_path %>